### ISSUE TITLE
React component frameworks and UI testing

### ISSUE THREAD

**Issue by tedkeep** [cdterry87/Resources#1]
Hi, I found this repo from the link you posted on reddit and I wanted to contribute. I saw that there is a Vue component framework section, and I know a couple React component frameworks that could be added:

- [Reactstrap](https://reactstrap.github.io/) 
- [Material UI](https://material-ui.com/) 

Additionally I know of a good UI testing tool which allows for components to be developed and tested in isolation:

- [Storybook](https://storybook.js.org/) 

I hope these are helpful resources to add to the list :)

**Comment by cdterry87** [comment]
Thanks for the contribution, @tedkeep ! Sorry I didn't see this sooner.  I have added these to the list! :)
